- name: This sets up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/6AMBATCH.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
  - name: Install httpd package
      package:
        name:
          - "httpd"
        state: present

  - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes  # Ensure httpd starts on boot

  - name: Create a simple index.html file
      copy:
        content: "<html><body><h1>Hello, Ansible!</h1></body></html>"
        dest: "/var/www/html/index.html"
  - name: Yum Install Packages
    yum: name={{item}} state=latest
    with_items:
       - wget
  - name: terraform install
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
